import type { Metadata } from 'next';
import {
  Inter,
  Roboto_Mono,
} from 'next/font/google';
import '@/styles/main.scss';
import clsx from 'clsx';


const inter = Inter({
  subsets: ['latin'],
  variable: '--textFont',
  weight: '400',
});
const roboto = Roboto_Mono({
  subsets: ['latin'],
  variable: '--titleFont',
  weight: '500',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
